# https://docs.github.com/pt/actions/learn-github-actions/usage-limits-billing-and-administration
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Eslint/Tests

env:
  NODE_VERSION: 18.*

on:
  pull_request:
    branches: 'SP-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build --if-present

      - name: Run Eslint
        run: npx eslint $(git diff --name-only HEAD | grep -E '\.(ts|jsx)$' | xargs)

      - name: Run Test
        run: npm test
