# https://docs.github.com/pt/actions/learn-github-actions/usage-limits-billing-and-administration
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Eslint/Tests

env:
  NODE_VERSION: 18.*

on:
  pull_request:
    branches: 'SP-*'
  push:
    branches: 'master'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Dependencies
        id: cache_dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-dependencies-${{ hashFiles('./package-lock.json')
            }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Run Eslint
        run: npx eslint $(git diff --name-only HEAD | grep -E '\.(ts|jsx)$' | xargs)

      - name: Run Test
        run: npm test
