# https://docs.github.com/pt/actions/learn-github-actions/usage-limits-billing-and-administration
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Eslint/Tests

env:
  NODE_VERSION: 20.10.0

on:
  pull_request:
    branches: '*'
  push:
    branches: 'master'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Eslint
        run: npx eslint $(git diff --name-only HEAD | grep -E '\.(ts|jsx)$' | xargs)
      - name: Run Test
        run: npm test
