name: Run Eslint/Tests

on:
  pull_request:
    branches: 'SP-**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.*
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build --if-present

      - name: Run Eslint
        run: npx eslint $(git diff --name-only --diff-filter=ACMRTUXB HEAD | grep '.ts$')

      - name: Run Test
        run: npm test
